services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: memoria
      POSTGRES_PASSWORD: testpassword
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  migrate:
    image: migrate/migrate
    volumes:
     - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:${DB_PASS}@postgres:5432/postgres?sslmode=disable", "up"]
    depends_on:
      - postgres
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5000:5000
    environment:
    - DB_USER=postgres
    - DB_PASS=${DB_PASS}
    - DB_HOST=postgres
    - DB_NAME=postgres
    - PORT=5000
    - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
    - MAPS_KEY=${MAPS_KEY}
    depends_on:
      - postgres