name: Go build and test

on:
  push:
    branches: [ release, master ]
    tags: [v*]
  pull_request:
    branches: [ release, master, feat/deliverable3 ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        cd app
        go build -v -o memoria

    - name: Test
      run: |
        cd app/test
        go test -v

  release:
    runs-on: ubuntu-latest
    if: github.ref_name == 'release' && github.event_name == 'push'
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: memoria
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}   

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push
      run: |
        cd app
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/memoria:1.0 .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/memoria:1.0